"""
report_generator.py
--------------------
Turns a dataframe of scored reviews into a human-readable, auto-generated
business intelligence report (Markdown), summarizing sentiment trends,
top aspects, and actionable recommendations.
"""

import pandas as pd
from datetime import datetime
from utils.text_utils import extract_aspects


def generate_bi_report(df: pd.DataFrame, model_name: str = "N/A") -> str:
    total = len(df)
    pos = (df["sentiment"] == "POSITIVE").sum()
    neg = (df["sentiment"] == "NEGATIVE").sum()
    neu = total - pos - neg
    pos_pct = pos / total * 100 if total else 0
    neg_pct = neg / total * 100 if total else 0
    neu_pct = neu / total * 100 if total else 0
    avg_conf = df["confidence"].mean() * 100 if total else 0

    # category breakdown
    cat_summary = (
        df.groupby("category")["sentiment"]
        .apply(lambda s: (s == "NEGATIVE").mean() * 100)
        .sort_values(ascending=False)
    )
    worst_category = cat_summary.index[0] if len(cat_summary) else "N/A"
    worst_category_pct = cat_summary.iloc[0] if len(cat_summary) else 0
    best_category = cat_summary.index[-1] if len(cat_summary) else "N/A"
    best_category_pct = cat_summary.iloc[-1] if len(cat_summary) else 0

    # top aspects
    pos_aspects = extract_aspects(df[df["sentiment"] == "POSITIVE"]["clean_review"].tolist(), top_n=5)
    neg_aspects = extract_aspects(df[df["sentiment"] == "NEGATIVE"]["clean_review"].tolist(), top_n=5)

    pos_aspect_str = ", ".join([f"**{a}** ({c} mentions)" for a, c in pos_aspects]) or "N/A"
    neg_aspect_str = ", ".join([f"**{a}** ({c} mentions)" for a, c in neg_aspects]) or "N/A"

    # overall verdict
    if neg_pct > 40:
        verdict = "⚠️ Customer sentiment is trending **negative**. Immediate attention recommended."
    elif neg_pct > 20:
        verdict = "🟡 Sentiment is **mixed**, with a notable share of dissatisfied customers."
    else:
        verdict = "✅ Overall customer sentiment is **healthy and positive**."

    recommendations = []
    if neg_aspects:
        top_complaint = neg_aspects[0][0]
        recommendations.append(
            f"Prioritize fixing issues related to **{top_complaint}** — it is the most frequently "
            f"cited complaint among negative reviews."
        )
    if worst_category_pct > 30:
        recommendations.append(
            f"The **{worst_category}** category has an elevated negative sentiment rate "
            f"({worst_category_pct:.1f}%). Consider a quality/process review for this line."
        )
    if pos_aspects:
        top_praise = pos_aspects[0][0]
        recommendations.append(
            f"Continue to invest in **{top_praise}**, which is the most praised aspect and a "
            f"potential differentiator in marketing."
        )
    if avg_conf < 70:
        recommendations.append(
            "Model confidence is moderate — consider fine-tuning on domain-specific data or "
            "collecting more labeled examples to improve reliability."
        )
    if not recommendations:
        recommendations.append("No critical issues detected. Maintain current quality and service standards.")

    report = f"""
# 📊 Business Intelligence Report — Customer Review Analysis

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Model used:** {model_name}
**Reviews analyzed:** {total}

---

## Executive Summary

{verdict}

| Metric | Value |
|---|---|
| Total Reviews | {total} |
| Positive | {pos} ({pos_pct:.1f}%) |
| Negative | {neg} ({neg_pct:.1f}%) |
| Neutral | {neu} ({neu_pct:.1f}%) |
| Avg. Model Confidence | {avg_conf:.1f}% |

---

## Category Insights

- **Highest negative sentiment:** {worst_category} ({worst_category_pct:.1f}% negative)
- **Lowest negative sentiment:** {best_category} ({best_category_pct:.1f}% negative)

---

## Aspect-Level Insights

**Top praised aspects:** {pos_aspect_str}

**Top complaint aspects:** {neg_aspect_str}

---

## Actionable Recommendations

{chr(10).join([f"{i+1}. {r}" for i, r in enumerate(recommendations)])}

---

*This report was auto-generated by the AI Review Intelligence Agent using transformer-based
sentiment classification ({model_name}) and keyword-based aspect extraction. For production
use, validate findings against a larger sample and human review.*
"""
    return report.strip()
